### ISSUE TITLE
相册按钮的处理应该由App自定义

### ISSUE THREAD

**Issue by imengyu** [mtjsoft/CameraXBarcodeScanning#1]
这是真的是非常棒的一个扫码组件！

不过美中不足的是使用中出现了相册按钮的小问题

相册按钮或许可以直接由App自定义逻辑，这样可以有更大的自由度，而不是在扫码组件中内置。

现在的问题有：

1. 根据 ScanningActivity.kt 140 行，点击相册按钮时，检查有没有 WRITE_EXTERNAL_STORAGE 权限，如果没有，这里是直接返回，而不是去动态申请权限，或者给出提示。
2. 库内置的PictureSelector组件与我的App中使用的PictureSelector组件冲突，导致其他地方无法使用PictureSelector，会报找不到类的错误。

或许可以考虑用户点击相册按钮时，返回一个特殊值，App调用者判断这个特殊值，自己打开相册，然后手动调用 scanningByUri 扫描文件，这样可有更大的自由度。

总的来说这是一个非常优秀的扫码组件，希望可以做的越来越好

**Comment by mtjsoft** [comment]
> 这是真的是非常棒的一个扫码组件！
> 
> 不过美中不足的是使用中出现了相册按钮的小问题
> 
> 相册按钮或许可以直接由App自定义逻辑，这样可以有更大的自由度，而不是在扫码组件中内置。
> 
> 现在的问题有：
> 
> 1. 根据 ScanningActivity.kt 140 行，点击相册按钮时，检查有没有 WRITE_EXTERNAL_STORAGE 权限，如果没有，这里是直接返回，而不是去动态申请权限，或者给出提示。
> 2. 库内置的PictureSelector组件与我的App中使用的PictureSelector组件冲突，导致其他地方无法使用PictureSelector，会报找不到类的错误。
> 
> 或许可以考虑用户点击相册按钮时，返回一个特殊值，App调用者判断这个特殊值，自己打开相册，然后手动调用 scanningByUri 扫描文件，这样可有更大的自由度。
> 
> 总的来说这是一个非常优秀的扫码组件，希望可以做的越来越好

V1.3.0已处理。相册按钮由APP自定义。
