### ISSUE TITLE
android.hardware.autofocus google play不支持

### ISSUE THREAD

**Issue by sanyuanzhang** [mtjsoft/CameraXBarcodeScanning#2]
库里面包含android.hardware.autofocus，导致很多设备在谷歌商店找不到我们的app

建议将清单文件中：<uses-feature android:name="android.hardware.autofocus" />
改为<uses-feature android:name="android.hardware.autofocus"  android:required="false"/>

![1704453448670](https://github.com/mtjsoft/CameraXBarcodeScanning/assets/7235223/344a9968-190f-4cce-b272-8014bdbaf6d0)

**Comment by sanyuanzhang** [comment]
建议将清单文件中：<uses-feature android:name="android.hardware.autofocus" /> 
改为 <uses-feature android:name="android.hardware.autofocus" android:required="false" />

**Comment by sanyuanzhang** [comment]
![Uploading 1704956194827.png…]()

**Comment by sanyuanzhang** [comment]
建议增加android:required="false"

**Comment by mtjsoft** [comment]
fix 1.3.1
